# Generated by Django 5.1 on 2024-08-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backend", "0055_remove_planfeature_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeatureGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("price_per_month", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                ("maximum_duration_months", models.IntegerField(blank=True, null=True)),
                ("stripe_product_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=100)),
                ("stripe_price_id", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                ("max_limit_per_month", models.IntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="billing.planfeaturegroup"),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="billing.subscriptionplan"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=100, null=True)),
                ("custom_subscription_price_per_month", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="billing.subscriptionplan"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(("organization__isnull", False), ("user__isnull", True)),
                            models.Q(("organization__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="billing_usersubscription_check_user_or_organization",
                    )
                ],
            },
        ),
    ]
