# Generated by Django 5.1 on 2024-08-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
