# Generated by Django 5.1 on 2024-08-30 15:55
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    UserSubscription = apps.get_model("billing", "UserSubscription")
    for row in UserSubscription.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_stripewebhookevent_usersubscription_uuid_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
