# Generated by Django 5.1 on 2024-08-30 15:55
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_auto_20240830_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
