# Generated by Django 4.2.5 on 2023-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date_uploaded",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
