# Generated by Django 4.2 on 2023-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound Sterling'), ('EUR', 'Euro'), ('USD', 'United States Dollar'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar')], default='GBP', max_length=3),
        ),
    ]
