# Generated by Django 4.2.5 on 2023-09-30 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0002_alter_usersettings_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Errors",
            new_name="Error",
        ),
        migrations.RenameModel(
            old_name="PasswordSecrets",
            new_name="PasswordSecret",
        ),
        migrations.RenameModel(
            old_name="TracebackErrors",
            new_name="TracebackError",
        ),
    ]
