# Generated by Django 4.1.7 on 2023-12-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_client_company_client_is_representative"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_is_representative",
            field=models.BooleanField(default=False),
        ),
    ]
