# Generated by Django 4.2.5 on 2023-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_remove_client_name_client_address_client_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
