# Generated by Django 4.2.7 on 2024-01-08 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_invoiceproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="merchant_store",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="purchase_category",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
