# Generated by Django 4.1.7 on 2023-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
    ]
