# Generated by Django 4.2.7 on 2024-01-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_receipt_merchant_store_receipt_purchase_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="merchant_store",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="purchase_category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
