# Generated by Django 4.1.7 on 2024-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_receiptdownloadtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="sort_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
