# Generated by Django 5.0.1 on 2024-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_invoice_sort_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptdownloadtoken",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
