# Generated by Django 5.0.1 on 2024-02-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_invoice_sort_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logged_in_as_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="backend.team",
            ),
        ),
    ]
