# Generated by Django 5.0.1 on 2024-02-04 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_user_logged_in_as_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams_leader_of",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
