# Generated by Django 4.2.5 on 2023-10-05 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0011_alter_teaminvitation_team_alter_teaminvitation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaminvitation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_invitations",
                to="backend.team",
            ),
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
