# Generated by Django 5.0.1 on 2024-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_auditlog_organization_client_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="extra_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="extra_value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
