# Generated by Django 4.1.7 on 2023-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_receipt_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=40),
        ),
    ]
