# Generated by Django 5.0.2 on 2024-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_alter_notification_user_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="allow_receipt_parsing",
            field=models.BooleanField(default=False),
        ),
    ]
