# Generated by Django 5.0.2 on 2024-02-14 19:26

from django.db import migrations, models

import settings.settings


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_alter_notification_user_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=settings.settings.CustomPrivateMediaStorage(),
                upload_to="invoice_logos",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="image",
            field=models.ImageField(
                storage=settings.settings.CustomPrivateMediaStorage(),
                upload_to="receipts",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=settings.settings.CustomPublicMediaStorage(),
                upload_to="profile_pictures/",
            ),
        ),
    ]
