# Generated by Django 4.2.5 on 2023-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_alter_notification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="action",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("modal", "Modal"),
                    ("redirect", "Redirect"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
    ]
