# Generated by Django 4.2.5 on 2023-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_alter_notification_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=100),
        ),
    ]
