# Generated by Django 5.0.2 on 2024-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0016_alter_invoice_logo_alter_receipt_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
