# Generated by Django 4.1.7 on 2023-10-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0017_alter_notification_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="last_name",
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
