# Generated by Django 4.2.5 on 2023-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_remove_invoice_client_invoice_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
