# Generated by Django 5.0.2 on 2024-02-23 19:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_alter_verificationcodes_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcodes",
            name="expiry",
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 22, 0, 25, 744643, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name="verificationcodes",
            name="token",
            field=models.TextField(default="XBNKTM", editable=False),
        ),
    ]
