# Generated by Django 4.2.5 on 2023-11-18 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0021_invoiceurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceurl",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
