# Generated by Django 4.2.5 on 2023-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0022_invoiceurl_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="name",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
