# Generated by Django 5.0.2 on 2024-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_loginlog_service_alter_verificationcodes_expiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("DEV", "Developer"), ("STAFF", "Staff"), ("USER", "User"), ("TESTER", "Tester"), ("CUSTOMER", "Customer")],
                default="USER",
                max_length=10,
            ),
        ),
    ]
