# Generated by Django 5.0.2 on 2024-02-27 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_user_is_customer_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managers",
            field=models.ManyToManyField(related_name="managed_clients", to=settings.AUTH_USER_MODEL),
        ),
    ]
