# Generated by Django 5.0.3 on 2024-03-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_apikey_invoiceonetimeschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceurl",
            name="never_expire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoiceurl",
            name="system_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invoiceurl",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
