# Generated by Django 5.0.2 on 2024-03-08 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_user_is_customer_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_number",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="managers",
            field=models.ManyToManyField(related_name="" "", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.team"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceproduct",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="logged_in_as_team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.team"),
        ),
    ]
