# Generated by Django 5.0.3 on 2024-03-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0024_invoiceurl_never_expire_invoiceurl_system_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceonetimeschedule",
            name="stored_schedule_arn",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
