# Generated by Django 5.0.2 on 2024-02-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0024_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="logged_in_as_team",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.team"),
        ),
    ]
