# Generated by Django 5.0.2 on 2024-03-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_alter_user_logged_in_as_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_number",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.team"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceproduct",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
