# Generated by Django 5.0.3 on 2024-03-29 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_alter_invoiceonetimeschedule_stored_schedule_arn"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
