# Generated by Django 5.0.3 on 2024-03-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0025_alter_invoiceonetimeschedule_stored_schedule_arn"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stored_schedule_arn", models.CharField(blank=True, max_length=500, null=True)),
                ("received", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("creating", "Creating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("deleting", "Deleting"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[("before_due", "Before Due"), ("after_due", "After Due"), ("on_overdue", "On Overdue")],
                        default="before_due",
                        max_length=100,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoice_reminders", to="backend.invoice"),
                ),
            ],
            options={
                "verbose_name": "Invoice Reminder",
                "verbose_name_plural": "Invoice Reminders",
            },
        ),
    ]
