# Generated by Django 5.0.3 on 2024-03-30 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_invoice_discount_amount_invoice_discount_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaLimit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(editable=False, max_length=100, unique=True)),
                ("name", models.CharField(editable=False, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                ("value", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustable", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Quota Limit",
                "verbose_name_plural": "Quota Limits",
            },
        ),
        migrations.CreateModel(
            name="QuotaOverrides",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quota_limit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quota_overrides", to="backend.quotalimit"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Quota Override",
                "verbose_name_plural": "Quota Overrides",
            },
        ),
    ]
