# Generated by Django 5.0.3 on 2024-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_invoicereminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
