# Generated by Django 5.0.3 on 2024-03-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_invoice_discount_amount_invoice_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("GBP", "British Pound Sterling"),
                    ("EUR", "Euro"),
                    ("USD", "United States Dollar"),
                    ("JPY", "Japanese Yen"),
                    ("INR", "Indian Rupee"),
                    ("AUD", "Australian Dollar"),
                    ("CAD", "Canadian Dollar"),
                ],
                default="GBP",
                max_length=3,
            ),
        ),
    ]
