# Generated by Django 5.0.3 on 2024-04-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0029_alter_invoice_organization_alter_invoice_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="items",
            field=models.ManyToManyField(blank=True, to="backend.invoiceitem"),
        ),
    ]
