# Generated by Django 5.0.4 on 2024-04-05 19:52
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0030_alter_invoice_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflags",
            name="description",
            field=models.TextField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="featureflags",
            name="name",
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
