# Generated by Django 5.0.4 on 2024-04-06 18:20
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0031_featureflags_description_alter_featureflags_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
