# Generated by Django 5.0.4 on 2024-04-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0031_featureflags_description_alter_featureflags_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.team"),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="EmailSendStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_status_at", models.DateTimeField(auto_now_add=True)),
                ("recipient", models.TextField()),
                ("aws_message_id", models.CharField(blank=True, editable=False, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("send", "Send"),
                            ("reject", "Reject"),
                            ("bounce", "Bounce"),
                            ("complaint", "Complaint"),
                            ("delivery", "Delivery"),
                            ("open", "Open"),
                            ("click", "Click"),
                            ("rendering_failure", "Rendering_Failure"),
                            ("delivery_delay", "Delivery_Delay"),
                            ("subscription", "Subscription"),
                            ("failed_to_send", "Failed_To_Send"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="emails_created", to="backend.team"
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="emailsendstatus",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("organization__isnull", False), ("user__isnull", True)),
                    models.Q(("organization__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="backend_emailsendstatus_check_user_or_organization",
            ),
        ),
    ]
