# Generated by Django 5.0.4 on 2024-04-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0032_client_email_verified_alter_client_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.team"),
        ),
    ]
