# Generated by Django 5.0.4 on 2024-04-07 22:34
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0034_alter_client_organization_alter_client_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsendstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("send", "Send"),
                    ("reject", "Reject"),
                    ("bounce", "Bounce"),
                    ("complaint", "Complaint"),
                    ("delivery", "Delivery"),
                    ("open", "Open"),
                    ("click", "Click"),
                    ("rendering_failure", "Rendering_Failure"),
                    ("delivery_delay", "Delivery_Delay"),
                    ("subscription", "Subscription"),
                    ("failed_to_send", "Failed_To_Send"),
                    ("pending", "Pending"),
                ],
                max_length=20,
            ),
        ),
    ]
