# Generated by Django 5.0.4 on 2024-06-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0035_client_contact_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="ClientDefaults",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GBP", "British Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "United States Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("INR", "Indian Rupee"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        default="GBP",
                        max_length=3,
                    ),
                ),
                ("invoice_due_date_value", models.PositiveSmallIntegerField(default=7)),
                (
                    "invoice_due_date_type",
                    models.CharField(
                        choices=[("days_after", "Days After"), ("date_following", "Date Following"), ("date_current", "Date Current")],
                        default="days_after",
                        max_length=20,
                    ),
                ),
                ("invoice_date_value", models.PositiveSmallIntegerField(default=15)),
                (
                    "invoice_date_type",
                    models.CharField(
                        choices=[("day_of_month", "Day Of Month"), ("days_after", "Days After")], default="day_of_month", max_length=20
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="client_defaults", to="backend.client"),
                ),
            ],
        ),
    ]
