# Generated by Django 5.0.4 on 2024-04-10 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0035_alter_emailsendstatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailsendstatus",
            name="updated_status_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
