# Generated by Django 5.0.4 on 2024-06-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0036_clientdefaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
