# Generated by Django 5.0.4 on 2024-06-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0036_alter_client_address_clientdefaults"),
        ("backend", "0036_apiauthtoken"),
    ]

    operations = []
