# Generated by Django 5.0.6 on 2024-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0038_alter_apiauthtoken_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiauthtoken",
            name="key",
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="active",
            field=models.BooleanField(default=True, help_text="If the key is active", verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="expired",
            field=models.BooleanField(default=False, help_text="If the key has expired", verbose_name="Expired"),
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="expires",
            field=models.DateTimeField(blank=True, help_text="Leave blank for no expiry", null=True, verbose_name="Expires"),
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, auto_created=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Last Used"),
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="name",
            field=models.CharField(default="bob", max_length=64, verbose_name="Key Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="key",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
