# Generated by Django 5.0.6 on 2024-06-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0039_apiauthtoken_active_apiauthtoken_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiauthtoken",
            name="scopes",
            field=models.JSONField(default=list, help_text="List of permitted scopes", verbose_name="Scopes"),
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="team",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tokens", to="backend.team"
            ),
        ),
        migrations.AlterField(
            model_name="apiauthtoken",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="apiauthtoken",
            name="key",
            field=models.CharField(max_length=40, unique=True, verbose_name="Key"),
        ),
        migrations.CreateModel(
            name="TeamMemberPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scopes", models.JSONField(default=list, help_text="List of permitted scopes", verbose_name="Scopes")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="permissions", to="backend.team")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="team_permissions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "user")},
            },
        ),
    ]
