# Generated by Django 5.0.6 on 2024-06-28 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0040_apiauthtoken_scopes_apiauthtoken_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiauthtoken",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
