# Generated by Django 5.0.6 on 2024-06-25 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0040_apiauthtoken_scopes_apiauthtoken_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceproduct",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.team"),
        ),
    ]
