# Generated by Django 5.0.6 on 2024-06-29 18:19
from django.contrib.auth.hashers import make_password
from django.db import migrations, models, transaction


def forwards_func(apps, schema_editor):
    APIAuthToken = apps.get_model("backend", "APIAuthToken")

    tokens = APIAuthToken.objects.all()

    for token in tokens:
        token.hashed_key = make_password(token.key, salt="api_tokens", hasher="default")

    with transaction.atomic():
        APIAuthToken.objects.bulk_update(tokens, ["hashed_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0041_alter_apiauthtoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiauthtoken",
            name="hashed_key",
            field=models.CharField(max_length=128, unique=True, null=True, verbose_name="Key"),
        ),
        migrations.RunPython(forwards_func),  # (cant really reverse)
        migrations.AlterField(
            model_name="apiauthtoken",
            name="hashed_key",
            field=models.CharField(max_length=128, unique=True, null=False, verbose_name="Key"),
        ),
        migrations.RemoveField(
            model_name="apiauthtoken",
            name="key",
        ),
    ]
