# Generated by Django 5.0.6 on 2024-06-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0042_remove_apiauthtoken_key_apiauthtoken_hashed_key"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quotaincreaserequest",
            old_name="user",
            new_name="requester",
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="owner_content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="owner_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailsendstatus",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailsendstatus",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceproduct",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.team"),
        ),
        migrations.AddField(
            model_name="invoiceproduct",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceproduct",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotaincreaserequest",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotaincreaserequest",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotaoverrides",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotaoverrides",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotausage",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quotausage",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="owner_content_type",
            field=models.ForeignKey(
                default=9,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "User")),
                    models.Q(("app_label", "backend"), ("model", "Team")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="owner_object_id",
            field=models.PositiveIntegerField(default=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoiceproduct",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
