# Generated by Django 5.0.6 on 2024-06-30 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    QuotaIncreaseRequest = apps.get_model("backend", "QuotaIncreaseRequest")

    objs = QuotaIncreaseRequest.objects.all()

    for obj in objs:
        obj.requester = obj.user

    QuotaIncreaseRequest.objects.bulk_update(objs, ["requester"])


def reverse_func(apps, schema_editor):
    pass
    # Reverse code not needed


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0042_remove_apiauthtoken_key_apiauthtoken_hashed_key"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Team",
            new_name="Organization",
        ),
        migrations.RemoveField(
            model_name="apiauthtoken",
            name="team",
        ),
        migrations.AddField(
            model_name="apiauthtoken",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AddField(
            model_name="invoiceproduct",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AddField(
            model_name="quotaincreaserequest",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AddField(
            model_name="quotaincreaserequest",
            name="requester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quota_increase_requests",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_code=reverse_func),
        migrations.AddField(
            model_name="quotaoverrides",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AddField(
            model_name="quotausage",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="emailsendstatus",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AlterField(
            model_name="emailsendstatus",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="invoiceproduct",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotaincreaserequest",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotaoverrides",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="quotausage",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="invoiceproduct",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("organization__isnull", False), ("user__isnull", True)),
                    models.Q(("organization__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="backend_invoiceproduct_check_user_or_organization",
            ),
        ),
    ]
