# Generated by Django 5.0.6 on 2024-06-30 16:04
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("backend", "User")
    Team = apps.get_model("backend", "Team")
    APIAuthToken = apps.get_model("backend", "APIAuthToken")

    content_type_user = ContentType.objects.get_for_model(User)
    content_type_team = ContentType.objects.get_for_model(Team)

    to_swap_organization = [
        apps.get_model("backend", "Receipt"),
        apps.get_model("backend", "Invoice"),
        apps.get_model("backend", "Client"),
        apps.get_model("backend", "AuditLog"),
        apps.get_model("backend", "QuotaUsage"),
        apps.get_model("backend", "InvoiceProduct"),
        apps.get_model("backend", "EmailSendStatus"),
        apps.get_model("backend", "QuotaIncreaseRequest"),
    ]

    for model in to_swap_organization:
        instances = model.objects.all()
        for instance in instances:
            if hasattr(instance, "user_id") and instance.user_id:
                instance.owner_content_type_id = content_type_user.id
                instance.owner_object_id = instance.user_id
            elif hasattr(instance, "organization_id") and instance.organization_id:
                instance.owner_content_type_id = content_type_team.id
                instance.owner_object_id = instance.organization_id
            elif hasattr(instance, "team_id") and instance.team_id:
                instance.owner_content_type_id = content_type_team.id
                instance.owner_object_id = instance.team_id

        # bulk save
        model.objects.bulk_update(instances, ["owner_content_type_id", "owner_object_id"])


def reverse_forwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_rename_user_quotaincreaserequest_requester_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=reverse_forwards_func),
    ]
