# Generated by Django 5.0.6 on 2024-07-18 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_rename_team_organization_remove_apiauthtoken_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultValues",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GBP", "British Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "United States Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("INR", "Indian Rupee"),
                            ("AUD", "Australian Dollar"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        default="GBP",
                        max_length=3,
                    ),
                ),
                ("invoice_due_date_value", models.PositiveSmallIntegerField(default=7)),
                (
                    "invoice_due_date_type",
                    models.CharField(
                        choices=[("days_after", "Days After"), ("date_following", "Date Following"), ("date_current", "Date Current")],
                        default="days_after",
                        max_length=20,
                    ),
                ),
                ("invoice_date_value", models.PositiveSmallIntegerField(default=15)),
                (
                    "invoice_date_type",
                    models.CharField(
                        choices=[("day_of_month", "Day Of Month"), ("days_after", "Days After")], default="day_of_month", max_length=20
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_values",
                        to="backend.client",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ClientDefaults",
        ),
        migrations.AddConstraint(
            model_name="defaultvalues",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("organization__isnull", False), ("user__isnull", True)),
                    models.Q(("organization__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="backend_defaultvalues_check_user_or_organization",
            ),
        ),
    ]
