# Generated by Django 5.0.7 on 2024-07-15 11:33

import settings.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_rename_team_organization_remove_apiauthtoken_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdefaults",
            name="default_invoice_logo",
            field=models.ImageField(
                blank=True, null=True, storage=settings.settings.CustomPrivateMediaStorage(), upload_to="invoice_logos"
            ),
        ),
    ]
