# Generated by Django 5.0.6 on 2024-07-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0043_rename_team_organization_remove_apiauthtoken_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("number", "Number"), ("checkbox", "Checkbox")], max_length=16, verbose_name="Type"
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="Visible")),
            ],
            options={
                "verbose_name": "Onboarding Field",
                "verbose_name_plural": "Onboarding Fields",
            },
        ),
        migrations.CreateModel(
            name="OnboardingForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("intro_text", models.TextField(blank=True, verbose_name="Intro")),
                ("btn_text", models.CharField(blank=True, default="Submit", max_length=50, verbose_name="Button Text")),
                ("response_text", models.TextField(blank=True, verbose_name="Response")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("send_customer_email", models.BooleanField(default=False, verbose_name="Send Email")),
                ("customer_email_subject", models.CharField(blank=True, max_length=200, verbose_name="Email Subject")),
                ("customer_email_body", models.TextField(blank=True, verbose_name="Email Body")),
                ("send_owner_email", models.EmailField(blank=True, max_length=254, verbose_name="Email Copy To")),
                ("owner_email_subject", models.CharField(blank=True, max_length=200, verbose_name="Email Subject")),
                ("owner_email_body", models.TextField(blank=True, verbose_name="Email Body")),
            ],
            options={
                "verbose_name": "Onboarding Form",
                "verbose_name_plural": "Onboarding Forms",
            },
        ),
        migrations.CreateModel(
            name="OnboardingFieldEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True, verbose_name="Value")),
                (
                    "field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="backend.onboardingfield"),
                ),
            ],
            options={
                "verbose_name": "Onboarding Field Entry",
                "verbose_name_plural": "Onboarding Field Entries",
            },
        ),
        migrations.AddField(
            model_name="onboardingfield",
            name="form",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="backend.onboardingform"),
        ),
    ]
