# Generated by Django 5.0.6 on 2024-07-02 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0044_onboardingfield_onboardingform_onboardingfieldentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingfield",
            name="order",
            field=models.PositiveSmallIntegerField(default=1000, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="onboardingfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("email", "Email"),
                    ("checkbox", "Checkbox"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Datetime"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingBooking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name="UUID")),
                ("primary_email", models.EmailField(max_length=254, verbose_name="Primary User Email")),
                ("name", models.CharField(blank=True, max_length=100, null=True, verbose_name="Name")),
                ("day", models.DateField(verbose_name="Day")),
                ("start_time", models.TimeField(verbose_name="Time")),
                ("end_time", models.TimeField(verbose_name="Time")),
                ("venue", models.CharField(max_length=100, verbose_name="Venue")),
                ("rooms", models.JSONField(default=list, verbose_name="Rooms")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("hourly_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Hourly Rate")),
                ("deposit", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Deposit")),
                ("deposit_paid", models.BooleanField(default=False, verbose_name="Deposit Paid")),
                ("is_confirmed", models.BooleanField(default=False, verbose_name="Confirmed")),
                ("is_cancelled", models.BooleanField(default=False, verbose_name="Cancelled")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At")),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Onboarding Booking",
                "verbose_name_plural": "Onboarding Bookings",
            },
        ),
    ]
