# Generated by Django 5.0.6 on 2024-07-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0044_defaultvalues_delete_clientdefaults_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="disabled_features",
            field=models.JSONField(default=list),
        ),
    ]
