# Generated by Django 5.0.6 on 2024-07-02 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0045_onboardingfield_order_alter_onboardingfield_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onboardingform",
            name="slug",
        ),
        migrations.AddField(
            model_name="onboardingfield",
            name="required",
            field=models.BooleanField(default=False, verbose_name="Required"),
        ),
        migrations.AddField(
            model_name="onboardingform",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name="UUID"),
        ),
    ]
