# Generated by Django 5.0.6 on 2024-07-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_alter_invoice_logo_alter_receipt_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerecurringset",
            name="day_of_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicerecurringset",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicerecurringset",
            name="month_of_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicerecurringset",
            name="schedule_arn",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="invoicerecurringset",
            name="schedule_name",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="invoicerecurringset",
            name="frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly"), ("yearly", "Yearly")], default="monthly", max_length=20
            ),
        ),
    ]
