# Generated by Django 5.0.7 on 2024-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_rename_status_invoicereminder_boto_schedule_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiauthtoken",
            name="administrator_service_type",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Administrator Service Type"),
        ),
    ]
