# Generated by Django 5.1 on 2024-08-23 11:13

import settings.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_rename_status_invoicereminder_boto_schedule_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultvalues",
            name="default_invoice_logo",
            field=models.ImageField(
                blank=True, null=True, storage=settings.settings.CustomPublicMediaStorage(), upload_to="invoice_logos/"
            ),
        ),
    ]
