# Generated by Django 5.0.6 on 2024-07-02 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_remove_onboardingform_slug_onboardingfield_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingform",
            name="organization",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
        ),
        migrations.AddField(
            model_name="onboardingform",
            name="user",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
