# Generated by Django 5.0.6 on 2024-07-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_invoicerecurringset_day_of_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_recurring_set",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.invoicerecurringset"),
        ),
    ]
