# Generated by Django 5.0.6 on 2024-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_onboardingform_organization_onboardingform_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="onboardingform",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("organization__isnull", False), ("user__isnull", True)),
                    models.Q(("organization__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="backend_onboardingform_check_user_or_organization",
            ),
        ),
    ]
