# Generated by Django 5.0.6 on 2024-07-03 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0048_onboardingform_backend_onboardingform_check_user_or_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingfield",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="UUID"),
        ),
        migrations.AlterField(
            model_name="onboardingfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("email", "Email"),
                    ("checkbox", "Checkbox"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Combined Datetime"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
