# Generated by Django 5.0.7 on 2024-07-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0048_invoice_invoice_recurring_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicerecurringset",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("paused", "paused"), ("cancelled", "cancelled")], default="ongoing", max_length=10
            ),
        ),
    ]
