# Generated by Django 5.0.6 on 2024-07-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0049_onboardingfield_uuid_alter_onboardingfield_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("checkbox", "Checkbox"),
                    ("date", "Date"),
                    ("time", "Time"),
                    ("datetime", "Combined Datetime"),
                ],
                max_length=16,
                verbose_name="Type",
            ),
        ),
    ]
