# Generated by Django 5.1 on 2024-08-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0050_multifileupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeatureGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "Free Plan"),
                            ("basic", "Basic Plan"),
                            ("standard", "Standard Plan"),
                            ("enterprise", "Enterprise Plan"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("price_per_month", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                ("maximum_duration_months", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(editable=False, max_length=100, unique=True)),
                ("name", models.CharField(editable=False, max_length=100)),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="backend.planfeaturegroup"),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="backend.subscriptionplan"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanFeatureVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.IntegerField(editable=False)),
                ("free_tier_limit", models.FloatField(default=0)),
                ("free_period_in_months", models.IntegerField(blank=True, null=True)),
                ("unit", models.CharField(max_length=20)),
                ("cost_per_unit", models.DecimalField(decimal_places=6, max_digits=10)),
                ("units_per_cost", models.FloatField(default=1)),
                ("minimum_billable_size", models.FloatField(blank=True, null=True)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("plan_feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="backend.planfeature")),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("unit", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(("organization__isnull", False), ("user__isnull", True)),
                            models.Q(("organization__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="backend_usage_check_user_or_organization",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="backend.planfeature")),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(("organization__isnull", False), ("user__isnull", True)),
                            models.Q(("organization__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="backend_userplan_check_user_or_organization",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("custom_subscription_price_per_month", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="backend.subscriptionplan"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(("organization__isnull", False), ("user__isnull", True)),
                            models.Q(("organization__isnull", True), ("user__isnull", False)),
                            _connector="OR",
                        ),
                        name="backend_usersubscription_check_user_or_organization",
                    )
                ],
            },
        ),
    ]
