# Generated by Django 5.1 on 2024-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0051_planfeaturegroup_subscriptionplan_planfeature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestoragefile",
            name="file_uri_path",
            field=models.CharField(default="/null/", max_length=500),
            preserve_default=False,
        ),
    ]
