# Generated by Django 5.1 on 2024-08-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0054_transferusage_storageusage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planfeature",
            name="group",
        ),
        migrations.RemoveField(
            model_name="planfeature",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="planfeatureversion",
            name="plan_feature",
        ),
        migrations.RemoveField(
            model_name="storageusage",
            name="feature",
        ),
        migrations.RemoveField(
            model_name="transferusage",
            name="feature",
        ),
        # migrations.RemoveField(
        #     model_name="storageusage",
        #     name="organization",
        # ),
        # migrations.RemoveField(
        #     model_name="storageusage",
        #     name="user",
        # ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="subscription_plan",
        ),
        # migrations.RemoveField(
        #     model_name="transferusage",
        #     name="user",
        # ),
        # migrations.RemoveField(
        #     model_name="usage",
        #     name="organization",
        # ),
        # migrations.RemoveField(
        #     model_name="usage",
        #     name="user",
        # ),
        # migrations.RemoveField(
        #     model_name="usersubscription",
        #     name="organization",
        # ),
        # migrations.RemoveField(
        #     model_name="usersubscription",
        #     name="user",
        # ),
        migrations.DeleteModel(
            name="PlanFeatureGroup",
        ),
        migrations.DeleteModel(
            name="PlanFeatureVersion",
        ),
        migrations.DeleteModel(
            name="PlanFeature",
        ),
        migrations.DeleteModel(
            name="StorageUsage",
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
        migrations.DeleteModel(
            name="TransferUsage",
        ),
        migrations.DeleteModel(
            name="Usage",
        ),
        migrations.DeleteModel(
            name="UserSubscription",
        ),
    ]
