# Generated by Django 5.1 on 2024-09-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0056_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="entitlements",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
