# Generated by Django 5.1 on 2024-09-08 14:30

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0058_organization_entitlements_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="invoicerecurringprofile",
            managers=[
                ("with_items", django.db.models.manager.Manager()),
            ],
        ),
    ]
