# Generated by Django 5.1 on 2024-09-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0059_alter_invoicerecurringprofile_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="require_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
