# Generated by Django 5.1 on 2024-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0060_user_require_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
