# Generated by Django 5.1 on 2024-09-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0061_defaultvalues_invoice_from_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_account_holder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_sort_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
