# Generated by Django 5.1 on 2024-09-28 18:46

import backend.core.data.default_email_templates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0062_defaultvalues_invoice_account_holder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultvalues",
            name="email_template_recurring_invoices_invoice_cancelled",
            field=models.TextField(
                default=backend.core.data.default_email_templates.recurring_invoices_invoice_cancelled_default_email_template
            ),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="email_template_recurring_invoices_invoice_created",
            field=models.TextField(
                default=backend.core.data.default_email_templates.recurring_invoices_invoice_created_default_email_template
            ),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="email_template_recurring_invoices_invoice_overdue",
            field=models.TextField(
                default=backend.core.data.default_email_templates.recurring_invoices_invoice_overdue_default_email_template
            ),
        ),
        migrations.AddField(
            model_name="defaultvalues",
            name="invoice_from_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
