# Generated by Django 5.1 on 2024-09-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0063_defaultvalues_email_template_recurring_invoices_invoice_cancelled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("pending", "Pending"), ("paid", "Paid")], default="pending", max_length=10
            ),
        ),
    ]
