# Generated by Django 5.1.1 on 2024-10-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0064_remove_invoice_payment_status_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceurl",
            name="never_expire",
        ),
        migrations.AddField(
            model_name="passwordsecret",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(choices=[("draft", "Draft"), ("pending", "Pending"), ("paid", "Paid")], default="draft", max_length=10),
        ),
        migrations.AlterField(
            model_name="invoiceurl",
            name="expires",
            field=models.DateTimeField(blank=True, help_text="When the item will expire", null=True, verbose_name="Expires"),
        ),
        migrations.AlterField(
            model_name="passwordsecret",
            name="expires",
            field=models.DateTimeField(blank=True, help_text="When the item will expire", null=True, verbose_name="Expires"),
        ),
        migrations.AlterField(
            model_name="teaminvitation",
            name="expires",
            field=models.DateTimeField(blank=True, help_text="When the item will expire", null=True, verbose_name="Expires"),
        ),
    ]
