# Generated by Django 5.1.1 on 2024-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0065_remove_invoiceurl_never_expire_passwordsecret_active_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKey",
        ),
        migrations.RemoveField(
            model_name="verificationcodes",
            name="expiry",
        ),
        migrations.AddField(
            model_name="verificationcodes",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="verificationcodes",
            name="expires",
            field=models.DateTimeField(blank=True, help_text="When the item will expire", null=True, verbose_name="Expires"),
        ),
    ]
