# Generated by Django 5.1.1 on 2024-10-13 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0066_delete_apikey_remove_verificationcodes_expiry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="UUID")),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("email", "Email"),
                            ("checkbox", "Checkbox"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("datetime", "Combined Datetime"),
                            ("description", "Text Description"),
                        ],
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="Visible")),
                ("required", models.BooleanField(default=True, verbose_name="Required")),
                ("order", models.PositiveSmallIntegerField(default=1000, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Onboarding Field",
                "verbose_name_plural": "Onboarding Fields",
            },
        ),
        migrations.CreateModel(
            name="OnboardingFieldEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True, verbose_name="Value")),
                (
                    "field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="backend.onboardingfield"),
                ),
            ],
            options={
                "verbose_name": "Onboarding Field Entry",
                "verbose_name_plural": "Onboarding Field Entries",
            },
        ),
        migrations.CreateModel(
            name="OnboardingForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("uuid", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name="UUID")),
                ("btn_text", models.CharField(blank=True, default="Submit", max_length=50, verbose_name="Button Text")),
                ("response_text", models.TextField(blank=True, verbose_name="Response")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("send_customer_email", models.BooleanField(default=False, verbose_name="Send Email")),
                ("customer_email_subject", models.CharField(blank=True, max_length=200, verbose_name="Email Subject")),
                ("customer_email_body", models.TextField(blank=True, verbose_name="Email Body")),
                ("send_owner_email", models.EmailField(blank=True, max_length=254, verbose_name="Email Copy To")),
                (
                    "organization",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.organization"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Onboarding Form",
                "verbose_name_plural": "Onboarding Forms",
            },
        ),
        migrations.AddField(
            model_name="onboardingfield",
            name="form",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="backend.onboardingform"),
        ),
        migrations.AddConstraint(
            model_name="onboardingform",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", False), ("user__isnull", True)),
                    models.Q(("organization__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="backend_onboardingform_check_user_or_organization",
            ),
        ),
    ]
