# Generated by Django 5.1.1 on 2024-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0068_invoice_created_at_invoice_status_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=300),
        ),
    ]
