# Generated by Django 5.1.1 on 2024-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0069_alter_auditlog_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_number",
        ),
        migrations.RemoveField(
            model_name="invoicerecurringprofile",
            name="invoice_number",
        ),
        migrations.RemoveField(
            model_name="invoicerecurringprofile",
            name="reference",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="reference",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
