# Generated by Django 5.1.5 on 2025-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0070_remove_invoice_invoice_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="public_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoicerecurringprofile",
            name="public_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
