# Generated by Django 5.1.5 on 2025-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0071_invoice_public_id_invoicerecurringprofile_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="public_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
