name: 💡 Suggest a new feature
description: If you have an idea for MyFinances, suggest it here!
title: "idea: "
labels: ["idea", "idea: suggested"]
body:
  - type: markdown
    attributes:
      value: |

        > Note: This is strictly for **feature requests**, issues setting up or bug reports be created with the "Report a Bug" form.

        Before creating the feature request, please make sure that you have done the following steps:
        - [ ] Checked our existing [feature requests](https://github.com/TreyWW/MyFinances/issues?q=is%3Aissue+label%3Aidea+)
        - [ ] Updated to the latest [official release](https://github.com/TreyWW/MyFinances/releases)
        
  - type: dropdown
    id: size
    validations:
      required: true
    attributes:
      label: How big is this feature?
      multiple: false
      options:
        - Small
        - Medium
        - Big feature
  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: Describe the problem
      description: |
        Please describe the problem needed to be solved in detail.

        You may paste links of any reference images, please upload directly by pasting into the comment (so it uploads through github). 
  - type: textarea
    id: solution
    validations:
      required: false
    attributes:
      label: Describe a possible solution
      description: |
          [OPTIONAL] Please describe a potential solution to the problem that we may be able to solve.

          Things you may want to address:
          - Details of the technical implementation
          - Tradeoffs made in design decisions
          - Caveats and considerations for the future
