import stripe

from settings.helpers import get_var

STRIPE_TEST_SECRET_KEY = get_var("STRIPE_TEST_SECRET_KEY")
STRIPE_LIVE_SECRET_KEY = get_var("STRIPE_LIVE_SECRET_KEY")
STRIPE_WEBHOOK_ENDPOINT_SECRET = get_var("STRIPE_WEBHOOK_ENDPOINT_SECRET")

STRIPE_MAIN_API_KEY = STRIPE_LIVE_SECRET_KEY if STRIPE_LIVE_SECRET_KEY else STRIPE_TEST_SECRET_KEY

STRIPE_LIVE_MODE = True if STRIPE_LIVE_SECRET_KEY else False

stripe.api_key = STRIPE_MAIN_API_KEY
