name: CI Tests

on:
  push:
    branches:
      - main
      - develop
      - fix/github_ci_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up environment variables
        run: cp .env.sample .env

      - name: Build and run docker-compose.ci.yml
        run: docker-compose -f infrastructure/backend/docker-compose.ci.yml up -d

      - name: Run the test scripts
        run: |
          docker-compose -f infrastructure/backend/docker-compose.ci.yml exec -T myfinances_django ./infrastructure/backend/scripts/tests/urls.sh
          docker-compose -f infrastructure/backend/docker-compose.ci.yml exec -T myfinances_django ./infrastructure/backend/scripts/tests/views.sh